### ISSUE TITLE
Shell commands master issue

### ISSUE THREAD

**Issue by danqing** [doubleproject/double-cli#4]
We need to come up with a spec of what to support through the CLI.

## Commands

- [x] `double` or `double help`: print the help text
- [x] `double init`: initialize a project (#9)
- [x] `double start` and `double restart`: start a network (#12)
- [x] `double status`: network status (#13)
- [x] `double clean`: clean a project/environment (#21)
